### ISSUE TITLE
Duplicate country code

### ISSUE THREAD

**Issue by lomirus** [Arcadyi/Cold-War-Project#18]
Hello! I just forked this repository and want to contribute the localization for other languages.  When I am translating, I found there are two country codes `AFG` and `AFH`, and both of them are for `Afghanistan`. Their ADJ codes are also for the same value `Afghan`. Is this an oversight?

**Comment by Arcadyi** [comment]
Its a bug with the way we built the countries, you can use the vanilla tag for all intents and purposes

**Comment by lomirus** [comment]
> Its a bug with the way we built the countries
So will the extra country tag be fixed in the future or still be kept?

> you can use the vanilla tag for all intents and purposes
Does this mean that the extra added country tag will not have real impact on the game?

**Comment by Arcadyi** [comment]
It will definitely be fixed later.
And yes there won't be any impact from the extra tag.
